create database titanic;
use titanic;

create table titanic_train(
PassengerId	int ,
Survived int ,
Pclass int ,
Name varchar(100),	
Sex	varchar(20),
Age	float ,
SibSp int ,	
Parch int ,	
Ticket varchar(50),
Fare float,	
Cabin varchar(50),	
Embarked varchar(50)
);

use titanic;
show tables;
desc titanic_train;
 
select * from titanic_train;
 
 -- Find the average fare for female?
select avg(Fare) as Avg_Fare from titanic_train
where sex='female';

-- What is average age of a male on ship?
select avg(Age) as Avg_Age from titanic_train
where sex = 'male';

-- What is the total fare earned from survived passangers?
select sum(Fare) as Total_Fare from titanic_train
where Survived=1;

-- What is average age of a survived female?
select avg(Age) as Avg_Age from titanic_train
where Survived=1 and sex='female';

-- What is average age of male survived?
select avg(Age) as Avg_Age from titanic_train
where Survived=1 and sex='male';

-- How many passengers were there on ship?
select count(*) as Count from titanic_train;

-- How many passangers survived?
select count(*) as Count from titanic_train
where Survived=1;

-- How many passangers were there in class 1?
select count(*) as Count from titanic_train
where Pclass=1;

-- How many passengers from class 1 survived?
select count(*) as Count from titanic_train
where Pclass=1 and Survived=1;

-- How many people embarked from S?
select count(*) as Count from titanic_train
where Embarked='s';

-- How many male passangers survived?
select count(*) as Count from titanic_train
where sex='male' and Survived=1;

-- How many female passangers embarked from S did not servive?
select count(*) as Count from titanic_train
where sex='female' and Survived=0 and Embarked='s';

-- How many class 2 male survived?
select count(*) as Count from titanic_train
where sex='male' and Survived=1 and Pclass=2;

-- What was average fare for class 2 passanger?
select avg(Fare) as Avg_Fare from titanic_train
where Pclass=2;

-- Find the highest fare.
select max(fare) as Highest_Fare from titanic_train;

-- Find the lowest fare.
select min(fare) as Lowest_Fare from titanic_train;

-- Find the total revenue generated by survived passangers.
select sum(Fare) as Total_Revenue from titanic_train
where Survived=1;

-- Find the total revenue generated by class 1 survived female.
select sum(Fare) as Total_Revenue from titanic_train
where Survived=1 and sex='female' and Pclass=1;

-- Find the total revenue generated by class 2 died male.
select sum(Fare) as Total_Revenue from titanic_train
where sex='male' and Pclass=2 and Survived=0;

-- Find the total revenue generated by passangers embarked from S and having age more than 30. 
select sum(Fare) as Total_Revenue from titanic_train
where Embarked='s' and age > 30;

-- How many passengers embarked from S having age more than 50 survived?
select count(*) as Count from titanic_train
where Embarked='s' and age > 50;

-- Find the eldest passenger.
select max(age) Max_Age from titanic_train;

-- Find the youngest passanger.
select min(age) as Min_Age from titanic_train;
